agents:
  queue: "public"

steps:
- name: "Go build"
  command: "go build -v -buildmode=c-shared -o /workdir/proxy/planetscale-linux.so.$BUILDKITE_COMMIT"
  artifact_paths:
    - "/workdir/proxy/*"
  plugins:
    - docker#v3.8.0:
        image: "golang:1.16.4"
- wait
- name: "Ruby build and test %n"
  command: "buildkite-agent artifact download /workdir/proxy/planetscale-linux.go.$BUILDKITE_COMMIT proxy/planetscale-linux.go && bundle exec rake test"
  plugins:
    - docker#v3.8.0:
        image: "ruby:2.7.3-slim"
