agents:
  queue: "public"
steps:
- name: "Ruby build and test %n"
  command: "go build -v -buildmode=c-shared -o proxy/planetscale-linux.so && bundle exec rake test"
  plugins:
    - docker#v3.8.0:
        image: ruby2.7.3-slim
