agents:
  queue: "public"

steps:
- name: "Go build"
  command: "go build -v -x -buildmode=c-shared -o planetscale-linux.so.$BUILDKITE_COMMIT && buildkite-agent artifact upload planetscale-linux.so.$BUILDKITE_COMMIT"
  plugins:
    - docker#v3.8.0:
        image: "golang:1.16.4"
- wait
- name: "Ruby build and test %n"
  command: "buildkite-agent artifact download planetscale-linux.so.$BUILDKITE_COMMIT proxy/planetscale-linux.go && bundle exec rake test"
  plugins:
    - docker#v3.8.0:
        image: "ruby:2.7.3-slim"
